on:
  pull_request:
  push:
jobs:
  test_ucm:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - run: |
        nix-build default.nix -A unison-ucm
        PATH='' ./result/bin/ucm version
        echo "pull stew.public.projects.uuid.latest lib.uuid" | \
          PATH='' ./result/bin/ucm --no-base
